name: tourio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
    
  get:
  sqflite:
  path_provider:
  path:
  google_fonts:
  intl:
  flutter_native_splash:
  lucide_icons:
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  get_storage: ^2.1.1
    

dev_dependencies:
  change_app_package_name:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:    
  uses-material-design: true
  assets:
    - assets/images/
